environment:
  matrix:
    - nodejs_version: 6.0.0
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set verify-store-integrity false
  # This breaks the tests in @pnpm/config, so commenting out for now
  # - npm set fetch-retry-maxtimeout 180000
  - set PNPM_VERSION=2.9.0
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
  - pnpm recursive install --no-lock
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm t
skip_tags: true
